### ISSUE TITLE
Only one AVR device possible

### ISSUE THREAD

**Issue by elektro-freak** [estbeetoo/node-red-contrib-eiscp#7]
First I would like to say I happy with this, because it is only EISCP tool I found where it is possible to send out MSG XML letter to the Pioneer MRX-5 and NR555 to connect them via flairconnect.

So I send out sommthing like MGS<mgs zone="1"><groupid>0</groupid><maxdelay>5000</maxdelay><devices><device id="0009B0E28C2B" zoneid="1" /></devices></mgs> as the msg.raw payload.

The issue I found out is, that if you have more than one device(controller), the node will everytime send the values to the first controller and not to the other ones. I think/hope that it is no be a big tdeal to fix. Would be nice if you could fix that soon. 

My work around is currenty using the onky implentation on the console of my raspberry for the devices where I don't need to send out the multiroom xml stuff.

thanks

**Comment by aborovsky** [comment]
Thanks for reporting! I’ll fix it soon, keep updated.

**Comment by TomItNet** [comment]
Till now I had one Onky connected and was very happy because I faced no problems.

Now I got two more Onkyo devices from which I would like to receive the status or switch them on or off. The two new Onkyo devices are of the same device type but different to the existing.

I observed a similar behavior as described above but not exactly the same:
Only one of the new Onkyo devices is connected.
At node red start it seems that it is tried  to establish the connection to both while one always fails. Maybe due to the fact that this is happening nearly at the same point in time.

Then I observed that also the communication to the older existing Onkyo is not possible any more.

As soon as I deactivate the new added eiscp connections ... 
![grafik](https://user-images.githubusercontent.com/52349743/71614629-1d5a1180-2bad-11ea-8356-970fb83eee33.png)
... the original one is working again.

I am not sure if there is only a general prpblem using several connections or if there is additional a behavoir if two devices of same type are used.

Any help would be nice.

**Comment by aborovsky** [comment]
Thx to @bendamat's PR, now it's fixed

**Comment by bendamat** [comment]
Hi @aborovsky, will you publish a new version to npm as well?

**Comment by aborovsky** [comment]
@bendamat published: https://www.npmjs.com/package/node-red-contrib-eiscp/v/0.3.3
sorry for delay :)
